spring:
  application:
    name: web_project_backend

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    #url: jdbc:postgresql://34.89.181.65:5432/postgres
    url: jdbc:postgresql://localhost:5432/movie_magic_db
    username: mfilaniu
    password: 123456Re
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
        format_sql: true
        show_sql: true


server:
  port: 1029





